services:
    backend:
        image: xeei/kupantip-backend:latest
        container_name: kupantip-backend
        ports:
            - '${PORT:-8000}:8000'
        networks:
          - kupantip-net

networks:
  kupantip-net:
    external: true