services:
    db:
        platform: 'linux/amd64'
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: 'Y'
            MSSQL_SA_PASSWORD: '${SQL_PASSWORD}'
        ports:
            - '1433:1433'
        volumes:
            - ./mssql/data:/var/opt/mssql/data
            - ./mssql/log:/var/opt/mssql/log
            - ./mssql/secrets:/var/opt/mssql/secrets

    backend:
        build: .
        image: backend-kupantip
        container_name: backend-kupantip
        ports:
            - '${PORT:-8000}:8000'
        env_file:
            - .env

    minio:
        image: minio/minio:latest
        command: server /data --console-address ":9001"
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            MINIO_ROOT_USER: '${MINIO_USER}'
            MINIO_ROOT_PASSWORD: '${MINIO_PASSWORD}'
        volumes:
            - ./minio-data:/data
