name: Docker Image CI

on:
    push:
        branches: [ "deployment-setup" ]
    workflow_dispatch:

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - name: 🚨 Checkout Repo
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Build Images
              run: |
                docker compose build
            
            - name: Tag & push Backend
              run: |
                docker tag kupantip-backend:latest ${{ secrets.DOCKER_USER }}/kupantip-backend:latest
                docker push ${{ secrets.DOCKER_USER }}/kupantip-backend:latest

            # - name: Tag & push Frontend
            #   run: |
            #     docker tag kupantip-frontend:latest ${{ secrets.DOCKER_USER }}/kupantip-frontend:latest
            #     docker push ${{ secrets.DOCKER_USER }}/kupantip-frontend:latest