name: Docker Image CI

on:
    push:
        branches: [ "main", "deployment-setup" ]
    workflow_dispatch:

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - name: 🚨 Checkout Repo
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Images & Tag & push Backend
              uses: docker/build-push-action@v6
              with:
                context: ./backend
                push: true
                tags: ${{ secrets.DOCKER_USER }}/kupantip-backend:latest

            - name: Build Images & Tag & push Frontend
              uses: docker/build-push-action@v6
              with:
                context: ./frontend
                push: true
                tags: ${{ secrets.DOCKER_USER }}/kupantip-frontend:latest
